/*global define*/

define([], function() {
    'use strict';

    var lang = lang || {};
    lang.en = {};

    lang.en.standard = {
        quarters: {
            1: 'Q1',
            2: 'Q2',
            3: 'Q3',
            4: 'Q4'
        },
        months: {
            1: 'January',
            2: 'February',
            3: 'March',
            4: 'April',
            5: 'May',
            6: 'June',
            7: 'July',
            8: 'August',
            9: 'September',
            10: 'October',
            11: 'November',
            12: 'December'
        },
        days: {
            1: 'Sunday',
            2: 'Monday',
            3: 'Tuesday',
            4: 'Wednesday',
            5: 'Thursday',
            6: 'Friday',
            7: 'Saturday'
        }
    };

    lang.en.frc = {
        quarters: {
            1: 'Autumn',
            2: 'Winter',
            3: 'Spring',
            4: 'Summer'
        },
        months: {
            1: 'Grape harvest',
            2: 'Fog',
            3: 'Frost',
            4: 'Snowy',
            5: 'Rainy',
            6: 'Windy',
            7: 'Germination',
            8: 'Flower',
            9: 'Pasture',
            10: 'Harvest',
            11: 'Summer heat',
            12: 'Fruit'
        },
        days: {
            1: {
                1: 'Grape',
                2: 'Saffron',
                3: 'Chestnut',
                4: 'Crocus',
                5: 'Horse',
                6: 'Impatiens',
                7: 'Carrot',
                8: 'Amaranth',
                9: 'Parsnip',
                10: 'Vat',
                11: 'Potato',
                12: 'Strawflower',
                13: 'Butter Squash',
                14: 'Mignonette',
                15: 'Donkey',
                16: 'The four o\'clock flower',
                17: 'Pumpkin',
                18: 'Buckwheat',
                19: 'Sunflower',
                20: 'Wine-Press',
                21: 'Hemp',
                22: 'Peach',
                23: 'Turnip',
                24: 'Amaryllis',
                25: 'Ox',
                26: 'Eggplant',
                27: 'Chili Pepper',
                28: 'Tomato',
                29: 'Barley',
                30: 'Barrel',
            },
            2: {
                1: 'Apple',
                2: 'Celery',
                3: 'Pear',
                4: 'Beet root',
                5: 'Goose',
                6: 'Heliotrope',
                7: 'Common Fig',
                8: 'Black Salsify',
                9: 'Chequer Tree',
                10: 'Plough',
                11: 'Salsify',
                12: 'Water chestnut',
                13: 'Jerusalem Artichoke',
                14: 'Endive',
                15: 'Turkey',
                16: 'Skirret',
                17: 'Watercress',
                18: 'Leadworts',
                19: 'Pomegranate',
                20: 'Harrow',
                21: 'Asarum baccharis',
                22: 'Azarole',
                23: 'Madder',
                24: 'Orange',
                25: 'Pheasant',
                26: 'Pistachio',
                27: 'Tuberous pea',
                28: 'Quince',
                29: 'Service tree',
                30: 'Roller',
            },
            3: {
                1: 'Rampion',
                2: 'Turnip',
                3: 'Chicory',
                4: 'Medlar',
                5: 'Pig',
                6: 'Corn Salad',
                7: 'Cauliflower',
                8: 'Honey',
                9: 'Juniper',
                10: 'Pickaxe',
                11: 'Wax',
                12: 'Horseradish',
                13: 'Cedar tree',
                14: 'Fir tree',
                15: 'Roe Deer',
                16: 'Gorse',
                17: 'Cypress Tree',
                18: 'Ivy',
                19: 'Savin Juniper',
                20: 'Grub-hoe',
                21: 'Sugar Maple',
                22: 'Heather',
                23: 'Reed plant',
                24: 'Sorrel',
                25: 'Cricket',
                26: 'Pinenut',
                27: 'Cork',
                28: 'Truffle',
                29: 'Olive',
                30: 'Shovel',
            },
            4: {
                1: 'Peat',
                2: 'Coal',
                3: 'Bitumen',
                4: 'Sulphur',
                5: 'Dog',
                6: 'Lava',
                7: 'Topsoil',
                8: 'Manure',
                9: 'Saltpeter',
                10: 'Flail',
                11: 'Granite stone',
                12: 'Clay',
                13: 'Slate',
                14: 'Sandstone',
                15: 'Rabbit',
                16: 'Flint',
                17: 'Marl',
                18: 'Limestone',
                19: 'Marble',
                20: 'Winnowing basket',
                21: 'Gypsum',
                22: 'Salt',
                23: 'Iron',
                24: 'Copper',
                25: 'Cat',
                26: 'Tin',
                27: 'Lead',
                28: 'Zinc',
                29: 'metal',
                30: 'Sieve',
            },
            5: {
                1: 'Spurge-laurel',
                2: 'Moss',
                3: 'Butcher\'s Broom',
                4: 'Snowdrop',
                5: 'Bull',
                6: 'Laurustinus',
                7: 'Tinder polypore',
                8: 'Daphne mezereum',
                9: 'Poplar Tree',
                10: 'Axe',
                11: 'Hellebore',
                12: 'Broccoli',
                13: 'Laurel',
                14: 'Filbert',
                15: 'Cow',
                16: 'Box Tree',
                17: 'Lichen',
                18: 'Yew tree',
                19: 'Lungwort',
                20: 'Billhook',
                21: 'Pennycress',
                22: 'Rose Daphne',
                23: 'Couch Grass',
                24: 'Common Knotgrass',
                25: 'Hare',
                26: 'Woad',
                27: 'Hazel',
                28: 'Cyclamen',
                29: 'Celandine',
                30: 'Sleigh',
            },
            6: {
                1: 'Coltsfoot',
                2: 'Dogwood',
                3: 'Matthiola',
                4: 'Privet',
                5: 'Billygoat',
                6: 'Wild Ginger',
                7: 'Italian Buckthorn',
                8: 'Violet',
                9: 'Goat Willow',
                10: 'Spade',
                11: 'Narcissus',
                12: 'Elm Tree',
                13: 'Common fumitory',
                14: 'Hedge Mustard',
                15: 'Goat',
                16: 'Spinach',
                17: 'Large-flowered Leopard\'s Bane',
                18: 'Pimpernel',
                19: 'Chervil',
                20: 'Twine',
                21: 'Mandrake',
                22: 'Parsley',
                23: 'Scurvy-grass',
                24: 'Daisy',
                25: 'Tuna',
                26: 'Dandelion',
                27: 'Wood Anemone',
                28: 'Maidenhair fern',
                29: 'Ash Tree',
                30: 'Dibber',
            },
            7: {
                1: 'Primrose',
                2: 'Plane Tree',
                3: 'Asparagus',
                4: 'Tulip',
                5: 'Hen',
                6: 'Chard Plant',
                7: 'Birch Tree',
                8: 'Daffodil',
                9: 'Alder',
                10: 'Hatchery',
                11: 'Periwinkle',
                12: 'Hornbeam',
                13: 'Morel',
                14: 'European Beech Tree',
                15: 'Bee',
                16: 'Lettuce',
                17: 'Larch',
                18: 'Hemlock',
                19: 'Radish',
                20: 'Hive',
                21: 'Judas tree',
                22: 'Lettuce',
                23: 'Horse chestnut',
                24: 'Arugula or Rocket',
                25: 'Pigeon',
                26: 'Lilac',
                27: 'Anemone',
                28: 'Pansy',
                29: 'Blueberry',
                30: 'Knife',
            },
            8: {
                1: 'Rose',
                2: 'Oak Tree',
                3: 'Fern',
                4: 'Hawthorn',
                5: 'Nightingale',
                6: 'Common Columbine',
                7: 'Lily of the Valley',
                8: 'Button mushroom',
                9: 'Hyacinth',
                10: 'Rake',
                11: 'Rhubarb',
                12: 'Sainfoin',
                13: 'Wallflower',
                14: 'Fan Palm tree',
                15: 'Silkworm',
                16: 'Comfrey',
                17: 'Salad Burnet',
                18: 'Basket of Gold',
                19: 'Orache',
                20: 'Garden hoe',
                21: 'Thrift',
                22: 'Fritillary',
                23: 'Borage',
                24: 'Valerian',
                25: 'Carp',
                26: 'shrub',
                27: 'Chive',
                28: 'Bugloss',
                29: 'Wild mustard',
                30: 'Shepherd\'s crook',
            },
            9: {
                1: 'Alfalfa',
                2: 'Daylily',
                3: 'Clover',
                4: 'Angelica',
                5: 'Duck',
                6: 'Lemon Balm',
                7: 'Oat grass',
                8: 'Martagon lily',
                9: 'Wild Thyme',
                10: 'Scythe',
                11: 'Strawberry',
                12: 'Woundwort',
                13: 'Pea',
                14: 'Acacia',
                15: 'Quail',
                16: 'Carnation',
                17: 'Elderberry',
                18: 'Poppy plant',
                19: 'Linden or Lime tree',
                20: 'Pitchfork',
                21: 'Cornflower',
                22: 'Camomile',
                23: 'Honeysuckle',
                24: 'Bedstraw',
                25: 'Tench',
                26: 'Jasmine Plant',
                27: 'Verbena',
                28: 'Thyme Plant',
                29: 'Peony Plant',
                30: 'Hand Cart',
            },
            10: {
                1: 'Rye',
                2: 'Oats',
                3: 'Onion',
                4: 'Speedwell',
                5: 'Mule',
                6: 'Rosemary',
                7: 'Cucumber',
                8: 'Shallot',
                9: 'Wormwood',
                10: 'Sickle',
                11: 'Coriander',
                12: 'Artichoke',
                13: 'Clove',
                14: 'Lavender',
                15: 'Chamois',
                16: 'Tobacco',
                17: 'Currant',
                18: 'Hairy Vetchling',
                19: 'Cherry',
                20: 'Park',
                21: 'Mint',
                22: 'Cumin',
                23: 'Bean',
                24: 'Alkanet',
                25: 'Guinea fowl',
                26: 'Sage Plant',
                27: 'Garlic',
                28: 'Tare',
                29: 'Wheat',
                30: 'Shawm',
            },
            11: {
                1: 'Spelt',
                2: 'Common Mullein',
                3: 'Melon',
                4: 'Ryegrass',
                5: 'Ram',
                6: 'Horsetail',
                7: 'Mugwort',
                8: 'Safflower',
                9: 'Blackberry',
                10: 'Watering Can',
                11: 'Switchgrass',
                12: 'Common Glasswort',
                13: 'Apricot',
                14: 'Basil',
                15: 'Ewe',
                16: 'Marshmallow',
                17: 'Flax',
                18: 'Almond',
                19: 'Gentian',
                20: 'Lock',
                21: 'Carline thistle',
                22: 'Caper',
                23: 'Lentil',
                24: 'Inula',
                25: 'Otter',
                26: 'Myrtle',
                27: 'Rapeseed',
                28: 'Lupin',
                29: 'Cotton',
                30: 'Mill',
            },
            12: {
                1: 'Plum',
                2: 'Millet',
                3: 'Puffball',
                4: 'Six-row Barley',
                5: 'Salmon',
                6: 'Tuberose',
                7: 'Winter Barley',
                8: 'Apocynum',
                9: 'Liquorice',
                10: 'Ladder',
                11: 'Watermelon',
                12: 'Fennel',
                13: 'Barberry',
                14: 'Walnut',
                15: 'Trout',
                16: 'Lemon',
                17: 'Teasel',
                18: 'Buckthorn',
                19: 'Mexican Marigold',
                20: 'Harvesting basket',
                21: 'Wild Rose',
                22: 'Hazelnut',
                23: 'Hops',
                24: 'Sorghum',
                25: 'Crayfish',
                26: 'Bitter Orange',
                27: 'Goldenrod',
                28: 'Maize or Corn',
                29: 'Sweet Chestnut',
                30: 'Pack Basket',
            }
        }
    };

    return lang;
});
