/*global define*/

define([], function () {
    'use strict';

    var lang = lang || {};
    lang.fr = {};

    lang.fr.standard = {
        quarters: {
            1: 'T1',
            2: 'T2',
            3: 'T3',
            4: 'T4'
        },
        months: {
            1: 'janvier',
            2: 'février',
            3: 'mars',
            4: 'avril',
            5: 'peut',
            6: 'juin',
            7: 'juillet',
            8: 'août',
            9: 'septembre',
            10: 'octobre',
            11: 'novembre',
            12: 'décembre'
        },
        days: {
            1: 'dimanche',
            2: 'lundi',
            3: 'mardi',
            4: 'mercredi',
            5: 'jeudi',
            6: 'vendredi',
            7: 'samedi'
        }
    };

    lang.fr.frc = {
        quarters: {
            1: 'Autumn',
            2: 'Hiver',
            3: 'Printemps',
            4: 'Été',
            5: 'Été'
        },
        months: {
            1: 'Vendémiaire',
            2: 'Brumaire',
            3: 'Frimaire',
            4: 'Nivôse',
            5: 'Pluviôse',
            6: 'Ventôse',
            7: 'Germinal',
            8: 'Floréal',
            9: 'Prairial',
            10: 'Messidor',
            11: 'Thermidor',
            12: 'Fructidor',
            13: 'Sansculottides'
        },
        days: {
            1: {
                1: 'Raisin',
                2: 'Safran',
                3: 'Châtaigne',
                4: 'Colchique',
                5: 'Cheval',
                6: 'Balsamine',
                7: 'Carotte',
                8: 'Amaranthe',
                9: 'Panais',
                10: 'Cuve',
                11: 'Pomme de terre',
                12: 'Immortelle',
                13: 'Potiron',
                14: 'Réséda',
                15: 'Âne',
                16: 'Belle de nuit',
                17: 'Citrouille',
                18: 'Sarrasin',
                19: 'Tournesol',
                20: 'Pressoir',
                21: 'Chanvre',
                22: 'Pêche',
                23: 'Navet',
                24: 'Amaryllis',
                25: 'Bœuf',
                26: 'Aubergine',
                27: 'Piment',
                28: 'Tomate',
                29: 'Orge',
                30: 'Tonneau'
            },
            2: {
                1: 'Pomme',
                2: 'Céleri',
                3: 'Poire',
                4: 'Betterave',
                5: 'Oie',
                6: 'Héliotrope',
                7: 'Figue',
                8: 'Scorsonère',
                9: 'Alisier',
                10: 'Charrue',
                11: 'Salsifis',
                12: 'Mâcre',
                13: 'Topinambour',
                14: 'Endive',
                15: 'Dindon',
                16: 'Chervis',
                17: 'Cresson',
                18: 'Dentelaire',
                19: 'Grenade',
                20: 'Herse',
                21: 'Bacchante',
                22: 'Azerole',
                23: 'Garance',
                24: 'Orange',
                25: 'Faisan',
                26: 'Pistache',
                27: 'Macjonc',
                28: 'Coing',
                29: 'Cormier',
                30: 'Rouleau'
            },
            3: {
                1: 'Raiponce',
                2: 'Turneps',
                3: 'Chicorée',
                4: 'Nèfle',
                5: 'Cochon',
                6: 'Mâche',
                7: 'Chou-fleur',
                8: 'Miel',
                9: 'Genièvre',
                10: 'Pioche',
                11: 'Cire',
                12: 'Raifort',
                13: 'Cèdre',
                14: 'Sapin',
                15: 'Chevreuil',
                16: 'Ajonc',
                17: 'Cyprès',
                18: 'Lierre',
                19: 'Sabine',
                20: 'Hoyau',
                21: 'Érable à sucre',
                22: 'Bruyère',
                23: 'Roseau',
                24: 'Oseille',
                25: 'Grillon',
                26: 'Pignon',
                27: 'Liège',
                28: 'Truffe',
                29: 'Olive',
                30: 'Pelle'
            },
            4: {
                1: 'Tourbe',
                2: 'Houille',
                3: 'Bitume',
                4: 'Soufre',
                5: 'Chien',
                6: 'Lave',
                7: 'Terre végétale',
                8: 'Fumier',
                9: 'Salpêtre',
                10: 'Fléau',
                11: 'Granit',
                12: 'Argile',
                13: 'Ardoise',
                14: 'Grès',
                15: 'Lapin',
                16: 'Silex',
                17: 'Marne',
                18: 'Pierre à chaux',
                19: 'Marbre',
                20: 'Van',
                21: 'Pierre à plâtre',
                22: 'Sel',
                23: 'Fer',
                24: 'Cuivre',
                25: 'Chat',
                26: 'Étain',
                27: 'Plomb',
                28: 'Zinc',
                29: 'Mercure',
                30: 'Crible'
            },
            5: {
                1: 'Lauréole',
                2: 'Mousse',
                3: 'Fragon',
                4: 'Perce-neige',
                5: 'Taureau',
                6: 'Laurier-thym',
                7: 'Amadouvier',
                8: 'Mézéréon',
                9: 'Peuplier',
                10: 'Coignée',
                11: 'Ellébore',
                12: 'Brocoli',
                13: 'Laurier',
                14: 'Avelinier',
                15: 'Vache',
                16: 'Buis',
                17: 'Lichen',
                18: 'If',
                19: 'Pulmonaire',
                20: 'Serpette',
                21: 'Thlaspi',
                22: 'Thimelé',
                23: 'Chiendent',
                24: 'Trainasse',
                25: 'Lièvre',
                26: 'Guède',
                27: 'Noisetier',
                28: 'Cyclamen',
                29: 'Chélidoine',
                30: 'Traîneau'
            },
            6: {
                1: 'Tussilage',
                2: 'Cornouiller',
                3: 'Violier',
                4: 'Troène',
                5: 'Bouc',
                6: 'Asaret',
                7: 'Alaterne',
                8: 'Violette',
                9: 'Marceau',
                10: 'Bêche',
                11: 'Narcisse',
                12: 'Orme',
                13: 'Fumeterre',
                14: 'Vélar',
                15: 'Chèvre',
                16: 'Épinard',
                17: 'Doronic',
                18: 'Mouron',
                19: 'Cerfeuil',
                20: 'Cordeau',
                21: 'Mandragore',
                22: 'Persil',
                23: 'Cochléaria',
                24: 'Pâquerette',
                25: 'Thon',
                26: 'Pissenlit',
                27: 'Sylvie',
                28: 'Capillaire',
                29: 'Frêne',
                30: 'Plantoir'
            },
            7: {
                1: 'Primevère',
                2: 'Platane',
                3: 'Asperge',
                4: 'Tulipe',
                5: 'Poule',
                6: 'Bette',
                7: 'Bouleau',
                8: 'Jonquille',
                9: 'Aulne',
                10: 'Couvoir',
                11: 'Pervenche',
                12: 'Charme',
                13: 'Morille',
                14: 'Hêtre',
                15: 'Abeille',
                16: 'Laitue',
                17: 'Mélèze',
                18: 'Ciguë',
                19: 'Radis',
                20: 'Ruche',
                21: 'Gainier',
                22: 'Romaine',
                23: 'Marronnier',
                24: 'Roquette',
                25: 'Pigeon',
                26: 'Lilas',
                27: 'Anémone',
                28: 'Pensée',
                29: 'Myrtille',
                30: 'Greffoir'
            },
            8: {
                1: 'Rose',
                2: 'Chêne',
                3: 'Fougère',
                4: 'Aubépine',
                5: 'Rossignol',
                6: 'Ancolie',
                7: 'Muguet',
                8: 'Champignon',
                9: 'Hyacinthe',
                10: 'Râteau',
                11: 'Rhubarbe',
                12: 'Sainfoin',
                13: 'Bâton d\'or',
                14: 'Chamerisier',
                15: 'Ver à soie',
                16: 'Consoude',
                17: 'Pimprenelle',
                18: 'Corbeille d\'or',
                19: 'Arroche',
                20: 'Sarcloir',
                21: 'Statice',
                22: 'Fritillaire',
                23: 'Bourrache',
                24: 'Valériane',
                25: 'Carpe',
                26: 'Fusain',
                27: 'Civette',
                28: 'Buglosse',
                29: 'Sénevé',
                30: 'Houlette'
            },
            9: {
                1: 'Luzerne',
                2: 'Hémérocalle',
                3: 'Trèfle',
                4: 'Angélique',
                5: 'Canard',
                6: 'Mélisse',
                7: 'Fromental',
                8: 'Martagon',
                9: 'Serpolet',
                10: 'Faux',
                11: 'Fraise',
                12: 'Bétoine',
                13: 'Pois',
                14: 'Acacia',
                15: 'Caille',
                16: 'Œillet',
                17: 'Sureau',
                18: 'Pavot',
                19: 'Tilleul',
                20: 'Fourche',
                21: 'Barbeau',
                22: 'Camomille',
                23: 'Chèvrefeuille',
                24: 'Caille-lait',
                25: 'Tanche',
                26: 'Jasmin',
                27: 'Verveine',
                28: 'Thym',
                29: 'Pivoine',
                30: 'Chariot'
            },
            10: {
                1: 'Seigle',
                2: 'Avoine',
                3: 'Oignon',
                4: 'Véronique',
                5: 'Mulet',
                6: 'Romarin',
                7: 'Concombre',
                8: 'Échalote',
                9: 'Absinthe',
                10: 'Faucille',
                11: 'Coriandre',
                12: 'Artichaut',
                13: 'Girofle',
                14: 'Lavande',
                15: 'Chamois',
                16: 'Tabac',
                17: 'Groseille',
                18: 'Gesse',
                19: 'Cerise',
                20: 'Parc',
                21: 'Menthe',
                22: 'Cumin',
                23: 'Haricot',
                24: 'Orcanète',
                25: 'Pintade',
                26: 'Sauge',
                27: 'Ail',
                28: 'Vesce',
                29: 'Blé',
                30: 'Chalémie'
            },
            11: {
                1: 'Épeautre',
                2: 'Bouillon blanc',
                3: 'Melon',
                4: 'Ivraie',
                5: 'Bélier',
                6: 'Prêle',
                7: 'Armoise',
                8: 'Carthame',
                9: 'Mûre',
                10: 'Arrosoir',
                11: 'Panic',
                12: 'Salicorne',
                13: 'Abricot',
                14: 'Basilic',
                15: 'Brebis',
                16: 'Guimauve',
                17: 'Lin',
                18: 'Amande',
                19: 'Gentiane',
                20: 'Écluse',
                21: 'Carline',
                22: 'Câprier',
                23: 'Lentille',
                24: 'Aunée',
                25: 'Loutre',
                26: 'Myrte',
                27: 'Colza',
                28: 'Lupin',
                29: 'Coton',
                30: 'Moulin'
            },
            12: {
                1: 'Prune',
                2: 'Millet',
                3: 'Lycoperdon',
                4: 'Escourgeon',
                5: 'Saumon',
                6: 'Tubéreuse',
                7: 'Sucrion',
                8: 'Apocyn',
                9: 'Réglisse',
                10: 'Échelle',
                11: 'Pastèque',
                12: 'Fenouil',
                13: 'Épine vinette',
                14: 'Noix',
                15: 'Truite',
                16: 'Citron',
                17: 'Cardère',
                18: 'Nerprun',
                19: 'Tagette',
                20: 'Hotte',
                21: 'Églantier',
                22: 'Noisette',
                23: 'Houblon',
                24: 'Sorgho',
                25: 'Écrevisse',
                26: 'Bigarade',
                27: 'Verge d\'or',
                28: 'Maïs',
                29: 'Marron',
                30: 'Panier'
            },
            13: {
                1: 'La Fête de la Vertu',
                2: 'La Fête du Génie',
                3: 'La Fête du Travail',
                4: 'La Fête de l\'Opinion',
                5: 'La Fête des Récompenses',
                6: 'La Fête de la Révolution'
            }
        }
    };

    return lang.fr;
});
